### ISSUE TITLE
TypeError reading useRef

### ISSUE THREAD

**Issue by studiosi** [greensock/react#10]
Hello,

I am just on a normal installation of NextJS in which I have been using GSAP for a while. 

When trying to use useGSAP for automatic cleanup, I get this error

```TypeError: Cannot read properties of null (reading 'useRef')```

which is generated on this line 

https://github.com/greensock/react/blob/b00905d1e00ce0b873e6c4b0cb09770254836b55/src/index.js#L32

I wonder if this is a problem with the usage of `useRef` or something that I am doing wrong.

**Comment by iDVB** [comment]
We saw this when attempting to run on react@rc (v19).

**Comment by s-pyadyshev** [comment]
same issue with react 19 beta, react, vite

**Comment by studiosi** [comment]
@jackdoyle  I have to say that yes, I have React installed (it is a working NextJS installation), I had already GSAP working (doing all the work manually) and that this is a type error.

Thanks for checking it out. I will try to create a minimal reproduction, but I think I am not the only one having this issue.

**Comment by studiosi** [comment]
I am closing this because I can't seem to be able to reproduce the issue. In case someone wants to check a minimal example of using GSAP inside of a Next.js app with TailwindCSS, I created this example while I was trying to make this error happen.

https://github.com/studiosi/gsap-react-example

**Comment by seismicsix** [comment]
For anyone who had the issue with react RC19...

You can add this to your package.json file to force the gsap plugin to reference the correct version of react.

`"overrides": {
      "@gsap/react": {
        "react": YOUR_REACT_RC_VERSION
      }
}`

hope this helps :-)

**Comment by paulrrdiaz** [comment]
Getting the same issue.
@seismicsix could you give more details about 
> "overrides": { "@gsap/react": { "react": YOUR_REACT_RC_VERSION } }
?

I've tried
```
"overrides": {
      "@gsap/react": {
            "react": "18.2.0"
      }
 }
```
but no luck, thanks in advance

**Comment by thesportslms** [comment]
> Getting the same issue. @seismicsix could you give more details about
> 
> > "overrides": { "@gsap/react": { "react": YOUR_REACT_RC_VERSION } }
> > ?
> 
> I've tried
> 
> ```
> "overrides": {
>       "@gsap/react": {
>             "react": "18.2.0"
>       }
>  }
> ```
> 
> but no luck, thanks in advance

YOUR_REACT_RC_VERSION  = should reference the react version 19 you're trying to install; so update;

>             "react": "18.2.0"

to something like

>             "react": "19.0.0-rc-??????-????"
