### ISSUE TITLE
Possible Improvement for for Remix.

### ISSUE THREAD

**Issue by skrichten** [greensock/react#12]
I ran into an issue while using useGSAP in a Remix project.  My dev build worked as expected, but in the production build useGSAP was never able to see my ref's to DOM elements.  Could it be related to this...
https://remix.run/docs/en/main/guides/gotchas#typeof-window-checks
useGSAP checks for `window` to decide whether to use useEffect or useLayoutEffect.  Wondering if using `document` would work here as the remix doc suggests?

**Comment by jackdoyle** [comment]
Interesting. That seems like an odd Remix behavior. It's probably okay to make that change to document - did you try that and verify that it resolves things for you in the useGSAP() hook?

**Comment by skrichten** [comment]
Sadly that change doesn't fix it.  Must be some other issue here.  I will make a new issue if I find it.
