### ISSUE TITLE
useGSAP does not cleanup properly when dependencies option is used

### ISSUE THREAD

**Issue by ParallelUniv3rse** [greensock/react#6]
Minimal reproduction is here: 

https://stackblitz.com/edit/react-pd8abu?file=src%2FApp.js

There seems to be an issue where the cleanup function does not run on component's unmount when dependency array in options is used. 

This behavior can be observed in the console logs in the reproduction. 
When dependencies are used: the cleanup message is not printed for the component which has been unmounted.
When dependencies are NOT used: the cleanup message prints for the unmounted component.

**Comment by jackdoyle** [comment]
Perhaps I'm misunderstanding you, but by default ```revertOnUpdate``` is ```false``` when there are dependencies, thus the animations don't revert the cleanup function isn't supposed to be called when the dependencies change. That's very intentional. If you want that behavior, though, just set ```revertOnUpdate: true```

Does that clear things up?

**Comment by ParallelUniv3rse** [comment]
Hi Jack, 
thank you for the reaction. 
Looking at the source code I've understood exactly what you're saying - that this behaviour is intentional and very much makes sense. 
Not reverting when dependencies change is clear, but what I do not understand is why would the hook not cleanup when the component unmounts (without setting `revertOnUpdate: true`, with it it does cleanup).

I've bumped into this issue when creating an instance of ScrollTrigger in the `useGSAP` callback.
Although I don't need to revert on variable updates I would expect that the returned cleanup function still runs when my component unmounts and the ScrollTrigger gets killed and is not left active and hanging around in memory.

Am I misunderstanding something or perhaps misusing the useGSAP hook in a way?

**Comment by jackdoyle** [comment]
Thanks for pointing that out - it should be resolved in the latest release. Sorry about the hassle there!
