### ISSUE TITLE
Issue in cleanup

### ISSUE THREAD

**Issue by hayyaun** [greensock/react#9]
Hi, it seems like cleanup is not working properly.

**Comment by jackdoyle** [comment]
Hi @hayyaun 

Why do you think cleanup isn't working properly? Can you please provide a minimal demo (like a Stackblitz) that clearly illustrates the issue? Nobody else has reported any cleanup issues. 

Here's a starter template you can fork: 
https://stackblitz.com/edit/react-cxv92j

**Comment by hayyaun** [comment]
> Hi @hayyaun 
> 
> Why do you think cleanup isn't working properly? Can you please provide a minimal demo (like a Stackblitz) that clearly illustrates the issue? Nobody else has reported any cleanup issues. 
> 
> Here's a starter template you can fork: 
> https://stackblitz.com/edit/react-cxv92j

Hi @jackdoyle, I've also seen a thread on Gsap forum about the exact same issue, I'll try to provide a minimal demo that represents it, sorry for the short description and thanks for the intact response.

**Comment by hayyaun** [comment]
@jackdoyle Here is the demo, do you think there's a problem with my implementation? since when I use the exact same logic with `useEffect` the cleanup works totally fine.

https://stackblitz.com/edit/react-ove6yh?file=src%2FApp.js

**Comment by hayyaun** [comment]
@jackdoyle After reading docs I noticed that there's an option called `revertOnUpdate`. Sorry for the confusion, this solved my issue.

**Comment by jackdoyle** [comment]
I'm glad that resolved it for you. It's not good to have checked by default because most developers want animations to get smoothly updated when a dependency is updated. They don't want things jumping back to the initial values (reverting). Sorry if any of that was confusing for you.

**Comment by hayyaun** [comment]
Oh I see now. I should've checked the docs completely. Thanks for your good information, I now know when to not use that revert option too. 🙏
